galeria/urls.py
from django.conf.urls import patterns, url

from galeria import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/fotos$', views.FotosView.as_view(), name='fotos'),
)

galeria/models.py
from django.db import models
import datetime
from django.utils import timezone

class Galeria(models.Model):
    title = models.CharField(max_length=50)
    tag = models.CharField(max_length=20)

    def __unicode__(self):
        return self.title

class Foto(models.Model):
    galeria = models.ForeignKey(Galeria)
    image_url = models.URLField()
    descricao = models.CharField(max_length=50)

    def __unicode__(self):
        return self.descricao

galeria/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from galeria.models import Foto, Galeria


class FotosView(generic.ListView):
    model = Foto
    template_name = 'galeria/fotos.html'

    def get_queryset(self):
        queryset = super(generic.ListView, self).get_queryset()
        return queryset.filter(galeria=self.kwargs['pk'])


class IndexView(generic.ListView):
    model = Galeria
    template_name = 'galeria/index.html'

    def get_context_data(self, **kwargs):
        dados = super(generic.ListView, self).get_context_data(**kwargs)
        dados['titulo'] = 'Galeria'
        return dados

galeria/templates/galeria/fotos.html
{% extends "home/base_site.html" %}

{% block conteudo %}

    {% if foto_list %}
    <h3>Minhas imagens</h3>
        <div class="row clearfix">
            <div id="meus-links" class="text-center">
                {% for foto in foto_list %}
                    <a href="#">{{ forloop.counter }}</a>
                {% endfor %}
            </div>
        </div>
        <ul>
        {% for foto in foto_list %}
            <li class="minha-foto">
                <img class="img-responsive" height="1200" width="900" src="{{ foto.image_url }}" alt="{{ foto.descricao }}">
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Essa galeria não tem foto</p>
    {% endif %}
{% endblock conteudo %}

galeria/templates/galeria/index.html
{% extends "home/base_site.html" %}

{% block conteudo %}
<h3>Minhas galerias</h3>
    {% if galeria_list %}
        {% for galeria in galeria_list %}
        <div class="foto-{{ galeria.id }}">
            <a href="{{ galeria.id }}/fotos">{{ galeria.title }}</a>
        </div>
        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock conteudo %}